kind: Secret
apiVersion: v1
metadata:
  name: szlog-clickhouse-operator
  namespace: platform
  labels:
    app.kubernetes.io/component: operator
    app.kubernetes.io/instance: szlog
    app.kubernetes.io/name: clickhouse
    app.kubernetes.io/version: 24.1.2
    clickhouse.altinity.com/chop: 0.21.2
    helm.sh/chart: clickhouse-24.1.6
  annotations:
    meta.helm.sh/release-name: szlog
    meta.helm.sh/release-namespace: platform
data:
  password: Y2xpY2tob3VzZV9vcGVyYXRvcl9wYXNzd29yZA==
  username: Y2xpY2tob3VzZV9vcGVyYXRvcg==
type: Opaque

