kind: Service
apiVersion: v1
metadata:
  name: my-release-k8s-infra-otel-deployment
  namespace: signoz
  labels:
    app.kubernetes.io/component: otel-deployment
    app.kubernetes.io/instance: my-release
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: k8s-infra
    app.kubernetes.io/version: 0.88.0
    helm.sh/chart: k8s-infra-0.11.10
  annotations:
    meta.helm.sh/release-name: my-release
    meta.helm.sh/release-namespace: signoz
spec:
  ports:
    - name: health-check
      protocol: TCP
      port: 13133
      targetPort: health-check
  selector:
    app.kubernetes.io/component: otel-deployment
    app.kubernetes.io/instance: my-release
    app.kubernetes.io/name: k8s-infra
  clusterIP: 10.233.56.4
  clusterIPs:
    - 10.233.56.4
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
