kind: ServiceAccount
apiVersion: v1
metadata:
  name: my-release-k8s-infra-otel-deployment
  namespace: signoz
  labels:
    app.kubernetes.io/component: otel-deployment
    app.kubernetes.io/instance: my-release
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: k8s-infra
    app.kubernetes.io/version: 0.88.0
    helm.sh/chart: k8s-infra-0.11.10
  annotations:
    meta.helm.sh/release-name: my-release
    meta.helm.sh/release-namespace: signoz
secrets:
  - name: my-release-k8s-infra-otel-deployment-token-bjctz
