kind: Service
apiVersion: v1
metadata:
  name: my-release-k8s-infra-otel-agent
  namespace: signoz
  labels:
    app.kubernetes.io/component: otel-agent
    app.kubernetes.io/instance: my-release
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: k8s-infra
    app.kubernetes.io/version: 0.88.0
    helm.sh/chart: k8s-infra-0.11.10
  annotations:
    meta.helm.sh/release-name: my-release
    meta.helm.sh/release-namespace: signoz
spec:
  ports:
    - name: health-check
      protocol: TCP
      port: 13133
      targetPort: health-check
    - name: metrics
      protocol: TCP
      port: 8888
      targetPort: metrics
    - name: otlp
      protocol: TCP
      port: 4317
      targetPort: otlp
    - name: otlp-http
      protocol: TCP
      port: 4318
      targetPort: otlp-http
  selector:
    app.kubernetes.io/component: otel-agent
    app.kubernetes.io/instance: my-release
    app.kubernetes.io/name: k8s-infra
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
