apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    meta.helm.sh/release-name: my-release
    meta.helm.sh/release-namespace: signoz
  creationTimestamp: "2024-09-10T05:05:01Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: my-release-k8s-infra-otel-agent-signoz
  resourceVersion: "41733205"
  uid: daa0c398-7e24-40cc-a168-ab802f19a989
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - replicasets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  - endpoints
  verbs:
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes/proxy
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - nodes/stats
  - configmaps
  - events
  verbs:
  - create
  - get
- apiGroups:
  - ""
  resourceNames:
  - otel-container-insight-clusterleader
  resources:
  - configmaps
  verbs:
  - get
  - update