kind: ServiceAccount
apiVersion: v1
metadata:
  name: szlog-signoz-alertmanager
  namespace: platform
  labels:
    app.kubernetes.io/component: alertmanager
    app.kubernetes.io/instance: szlog
    app.kubernetes.io/name: signoz
    app.kubernetes.io/version: 0.52.0
    helm.sh/chart: signoz-0.50.0
  annotations:
    meta.helm.sh/release-name: szlog
    meta.helm.sh/release-namespace: platform

