kind: ServiceAccount
apiVersion: v1
metadata:
  name: szlog-clickhouse
  namespace: platform
  labels:
    app.kubernetes.io/component: clickhouse
    app.kubernetes.io/instance: szlog
    app.kubernetes.io/name: clickhouse
    app.kubernetes.io/version: 24.1.2
    helm.sh/chart: clickhouse-24.1.6
  annotations:
    meta.helm.sh/release-name: szlog
    meta.helm.sh/release-namespace: platform

